#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# compilr the code -------------------------------------------------------------
printf "Compiling the code:\n"
# main code ---------------------
printf "tqd_n.cpp.............."
g++ -o tqd-c tqd_n.cpp

rc=$?;
if [[ $rc == 0 ]];
then printf "done\n";
fi

chmod +x tqd-c

# code for check input file --------
printf "check_input_file.cpp..."
g++ -o check_input_file check_input_file.cpp

rc=$?;
if [[ $rc == 0 ]];
then printf "done\n";
fi

chmod +x check_input_file


printf "\nDo you want to add this script to the path (yes/no)? "
read response

if [[ ($response == "yes") || ($response == "y") ]];
then
  LINE="export PATH=\"\$PATH:$DIR\""
  printf "adding %s to your \$PATH..." "$DIR"

  printf '\n#threshold q-gram distance dir path\n%s\n' "$LINE" >> ~/.profile
  rc=$?;
  if [[ $rc == 0 ]];
  then printf "done\n";
  fi

fi
